export type LocationDefinition = {
  name: string;
  effect: string;
};

export const locations: LocationDefinition[] = [
  { name: "Ruins", effect: "This location has no effects." },
  { name: "Alchemical Fallout", effect: "Ruin one of the other locations after round 4." },
  { name: "Tinkerer's Toolbox", effect: "Both players draw a random <color=#01CE73>1-cost</color> card from their deck." },
  { name: "Anti-Magic Vault", effect: "Minion abilities are disabled here." },
  { name: "Mirror Dimension", effect: "<b>On Reveal</b> abilities happen twice here." },
  { name: "Burial Grounds", effect: "<b>On Death</b> abilities happen twice here." },
  { name: "Vacant Armory", effect: "Minions here have <b><color=#ffc829>+1 power</color></b>." },
  { name: "Arcane Ley Line", effect: "Both players get <color=#01CE73>+2 mana</color> this round." },
  { name: "Cloning Lab", effect: "After you play a minion here, fill your side with copies of it." },
  { name: "Sherwood Forest", effect: "Summon a Merry Man at a random location every turn." },
  { name: "Gold Spinning Wheel", effect: "All cards <color=#01CE73>cost 1 less</color> to play." },
  { name: "Tidal Pools", effect: "After combat, the <b><color=#ffc829>lowest power</color></b> minion(s) here get <b><color=#ffc829>+1 power</color></b>." },
  { name: "Overloaded Circuit", effect: "The first player to fill this location with minions deals <b><color=red>5 damage</color></b> to the enemy barrier here." },
  { name: "Soul Artillery", effect: "After a minion dies here, deal <b><color=red>1 damage</color></b> to its owner's barrier." },
  { name: "Training Dojo", effect: "After combat, minions here get <b><color=#ffc829>+1 power</color></b>." },
  { name: "Yaga's Bonefire", effect: "After a friendly minion dies, a friendly minion here gets <b><color=#ffc829>+1 power</color></b>." },
  { name: "Retribution Grounds", effect: "After a minion dies here, deal <b><color=red>1 damage</color></b> to its opponent's barrier." },
  { name: "Emerald City", effect: "After a minion is moved to this location, it gets <b><color=#ffc829>+2 power</color></b> and <b><color=red>+2 health</color></b>." },
  { name: "Conveyor Belt", effect: "After combat, move all minions here one space to the right." },
  { name: "Reflecting Pool", effect: "After you play a minion here, copy it to another random location." },
  { name: "Knowledge Vault", effect: "The first player to fill this location with minions draws a card." },
  { name: "Ante Up", effect: "After a friendly minion enters play here, deal <b><color=red>1 damage</color></b> to your barrier." },
  { name: "Library of Alexandria", effect: "When your barrier here is destroyed, draw a card." },
  { name: "Valhalla", effect: "If your barrier here has been destroyed, all friendly minions have <b><color=#ffc829>+2 power</color></b>." },
  { name: "Wall of Dumpty", effect: "Destroy the first minion you play here." },
  { name: "Hunting Grounds", effect: "Minions here have \"<b>On Kill:</b> I get <b><color=#ffc829>+2 power</color></b>\"." },
  { name: "The Hill", effect: "If there is more than one minion here after combat, destroy the <b><color=#ffc829>lowest-power</color></b> minions." },
  { name: "Castle in the Clouds", effect: "Cards that <b><color=#01CE73>cost 7</color></b> or higher <b><color=#01CE73>cost 1</color></b> less to play." },
  { name: "City of Thieves", effect: "Draw from your opponents deck instead of your own." },
  { name: "Stomping Grounds", effect: "Minions here have <b>Trample</b>." },
  { name: "Wonderland", effect: "Combat order is reversed." },
  { name: "Hundred Acre Woods", effect: "Summon Christopher Robin here for both players." },
  { name: "Field of Mice", effect: "When a minion enters play here, <b>Stun</b> it." },
  { name: "Scales of Justice", effect: "If you are losing this location, your minions here have <b><color=#ffc829>+2 power</color></b>." },
  { name: "Windy Woods", effect: "At the end of combat, minions here have a 50% chance of moving to another location." },
  { name: "Hero Emerges", effect: "Draw your legendary. Draw a card if you can't." },
  { name: "Poison Grounds", effect: "Minions here have <b>Deathtouch</b>." },
  { name: "Tectonic Decay", effect: "Deal <b><color=red>1 damage</color></b> to both barriers here at the end of combat." },
  { name: "Power Catalyst", effect: "While this location is full all your minions have <b><color=#ffc829>+2 power</color></b> and <b><color=red>+2 health</color></b>." },
  { name: "Isochronal Equilibrium", effect: "You can only play cards here on even turns." },
  { name: "Sapping Tree", effect: "Minions here have <b><color=#ffc829>-1 power</color></b> and <b><color=red>-1 health</color></b>." },
  { name: "Nostradamus' Call", effect: "At the start of turn 5, destroy both player's decks." },
  { name: "Amplifying Amphitheatre", effect: "All <b><color=red>damage</color></b> here is doubled." },
  { name: "Opposite Day", effect: "When you play a minion here, swap its stats." },
  { name: "Wukong's Solitude", effect: "If you only have 1 minion here, it has <b><color=#ffc829>+3 power</color></b> and <b><color=red>+3 health</color></b> and <b>Defender</b>." },
  { name: "Giant's Beacon", effect: "Draw your most expensive card. Set its <color=#01CE73>cost to 1</color>." },
  { name: "\"Human\" Cannon", effect: "When you play a minion here, destroy it and deal it's <b><color=#ffc829>power</color></b> as <b><color=red>damage</color></b> to the enemy barrier here." },
  { name: "Blessed Grounds", effect: "When a minion enters play here, give it <b>Shield</b>." },
  { name: "Poltergeist Party", effect: "Draw cards from your opponents deck instead of your own." },
  { name: "Heart of the Sea", effect: "At combat start, minions merge into the left-most, gaining their <b><color=#ffc829>power</color></b> and <b><color=red>health</color></b>." },
  { name: "Ashen Grove", effect: "When you play a minion here, discard your rightmost card and then draw a card." },
  { name: "Veterans Monument", effect: "When a barrier here is destroyed, give ALL minions <b><color=#ffc829>+1 power</color></b> and <b><color=red>+1 health</color></b>." },
  { name: "Treasure Trove", effect: "At the start of each round, add a <b>Gold Coin</b> to an empty space for each player here." },
  { name: "Gingerbread Grove", effect: "At the start of each round, add a <b>Cookie</b> to an empty space for each player here." },
  { name: "The Crucible", effect: "When a friendly minion dies here, give another friendly minon <b><color=#ffc829>+1 power</color></b> and <b><color=red>+1 health</color></b>." },
  { name: "Bakery", effect: "The first time a barrier here is destroyed, fill ALL spaces with Cookies and Cakes." },
  { name: "Broken Gate", effect: "Barriers here regenerate with <b><color=red>10 health</color></b> instead of <b><color=red>40 health</color></b>." },
  { name: "Bandersnatch Burrow", effect: "After you play a minion here, there is a 10% chance it will transform into a Bandersnatch this round." },
  { name: "Magic Mushroom", effect: "After you play a minion here, transform it into a minion that <color=#01CE73>costs 1 more</color>." },
  { name: "Narrow Corridor", effect: "You can only play one minion at this location every turn." },
  { name: "Chicken Coop", effect: "The first time you play a minion here each round, draw a card. If both players played minions here this round, destroy all minions here." },
];
